### ISSUE TITLE
Derreferenceability on URIs

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/cfkg#1]
`https://w3id.org/ecfkg/i/` should redirect somewhere, not produce 404!

**Comment by stefanogermano** [comment]
Well spotted!

Where should that redirect?
Is this something we need to change on W3ID?

**Comment by dgarijo** [comment]
Yes, but before we need to set up a service to handle the requests. I can
handle that but need some time

**Comment by dgarijo** [comment]
Example: https://w3id.org/ecfkg/i/UK/BEIS/2021/CF_1
