### ISSUE TITLE
Set up a proper SPARQL query interface in front of the endpoint

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/cfkg#5]
We need it to ease doing queries

**Comment by inaja** [comment]
Has this been fixed so I can add the link to the TEC-toolkit website?

**Comment by dgarijo** [comment]
The sparql endpoint is up, but there is no UI. I am working on that

**Comment by dgarijo** [comment]
Available at https://query.cf.linkeddata.es/query
